word1 =input ("noun")
word2 =input ("adgective")
word3 =input ("verb")
word4 =input ("adgective")
word5 =input ("noun")
word6 =input ("name")
word7 =input ("verb")
word8= input ("noun")
word9= input ("color")
word10= input ("adgective")
print ("when you were walking to" + word1)
print ("you ran into your" + word2 + "friend.")
print ("you decided to" + word3 + "to them.")
print ("she looked" + word4 + "so you hugged her.")
print ("apparently, she lost her" + word5)
print ("you decided to ask" +word6 + "about it.")
print ("but when you tried to ask, he" +word7)
print ("he finally told you that he lost his own" + word8 + "and he thought you took it.")
print ("you all got together to look for them and found a" +word9 + "jacket that belonged to you.")
print ("but you didn't manage to find your friend's things. You felt" +word10)
